language: cpp
compiler:
- g++
os:
- linux
script: make && make test && chmod +x ./script/run_ut.sh && ./script/run_ut.sh
env:
  global:
   - CODECOV_TOKEN="f4c49bd5-7f9e-44b3-86cf-ff800b26b19d"
   - ACOV="yes" # for cov flags

addons:
  apt:
    packages: lcov
    
after_success:
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info 'deps/*' --output-file coverage.info # filter deps-files
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

